import type { Product } from "./types"

export const featuredProducts: Product[] = [
  {
    id: 1,
    name: "Set Keranjang Serat Kelapa",
    description: "Keranjang anyaman tangan yang terbuat dari serat kelapa berkelanjutan",
    price: 29.99,
    discount: 0,
    image: "/images/product-1.webp",
    category: "Dekorasi Rumah",
    material: "Serat Kelapa",
    isNew: true,
    featured: true,
    createdAt: "2023-05-15",
  },
  {
    id: 2,
    name: "Set Peralatan Makan Bambu",
    description: "Peralatan makan ramah lingkungan dari bambu untuk makan berkelanjutan",
    price: 19.99,
    originalPrice: 24.99,
    discount: 20,
    image: "/images/product-2.webp",
    category: "Dapur",
    material: "Bambu",
    isNew: false,
    featured: true,
    createdAt: "2023-06-10",
  },
  {
    id: 3,
    name: "Pot Tanaman dari Sabut Kelapa",
    description: "Pot tanaman alami yang terbuat dari sabut kelapa",
    price: 15.99,
    discount: 0,
    image: "/images/product-3.webp",
    category: "Taman",
    material: "Sabut",
    isNew: false,
    featured: true,
    createdAt: "2023-04-20",
  },
  {
    id: 4,
    name: "Set Alas Meja Bambu",
    description: "Alas meja elegan yang dibuat dengan tangan dari bambu",
    price: 24.99,
    discount: 0,
    image: "/images/product-4.webp",
    category: "Dapur",
    material: "Bambu",
    isNew: true,
    featured: true,
    createdAt: "2023-07-05",
  },
]

export const allProducts: Product[] = [
  ...featuredProducts,
  {
    id: 5,
    name: "Tempat Lilin dari Batok Kelapa",
    description: "Tempat lilin indah yang terbuat dari batok kelapa",
    price: 12.99,
    discount: 0,
    image: "/images/product-5.webp",
    category: "Dekorasi Rumah",
    material: "Serat Kelapa",
    isNew: false,
    featured: false,
    createdAt: "2023-03-15",
  },
  {
    id: 6,
    name: "Hiasan Dinding Bambu",
    description: "Hiasan dinding dekoratif yang terbuat dari potongan bambu",
    price: 34.99,
    discount: 0,
    image: "/images/product-6.webp",
    category: "Dekorasi Rumah",
    material: "Bambu",
    isNew: false,
    featured: false,
    createdAt: "2023-02-28",
  },
  {
    id: 7,
    name: "Keset Serat Kelapa",
    description: "Keset tahan lama yang terbuat dari serat kelapa",
    price: 22.99,
    originalPrice: 29.99,
    discount: 23,
    image: "/images/product-7.webp",
    category: "Dekorasi Rumah",
    material: "Serat Kelapa",
    isNew: false,
    featured: false,
    createdAt: "2023-01-10",
  },
  {
    id: 8,
    name: "Tempat Peralatan Dapur Bambu",
    description: "Tempat peralatan dapur yang bergaya terbuat dari bambu",
    price: 18.99,
    discount: 0,
    image: "/images/product-8.webp",
    category: "Dapur",
    material: "Bambu",
    isNew: false,
    featured: false,
    createdAt: "2023-05-22",
  },
]
